import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [
    daisyui,
  ],
  daisyui: {
    themes: [
      {
        light: {
          "color-scheme": "light",
          "primary": "#3b82f6",
          "primary-content": "#ffffff",
          "secondary": "#f000b8",
          "secondary-content": "#ffffff",
          "accent": "#37cdbe",
          "accent-content": "#163835",
          "neutral": "#3d4451",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#e5e7eb",
          "base-content": "#1f2937",
          "info": "#2094f3",
          "success": "#009485",
          "warning": "#ff9900",
          "error": "#ff5724",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.5rem",
          "--border-color": "var(--fallback-b3, oklch(var(--b3) / 0.2))",
          "--btn-focus-scale": "0.95",
          "--tab-border": "2px",
        },
        dark: {
          "color-scheme": "dark",
          "primary": "#3b82f6",
          "primary-content": "#ffffff",
          "secondary": "#f000b8",
          "secondary-content": "#ffffff",
          "accent": "#37cdbe",
          "accent-content": "#163835",
          "neutral": "#1f2937",
          "neutral-content": "#ffffff",
          "base-100": "#111827",
          "base-200": "#1f2937",
          "base-300": "#374151",
          "base-content": "#f9fafb",
          "info": "#2094f3",
          "success": "#009485",
          "warning": "#ff9900",
          "error": "#ff5724",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.5rem",
          "--border-color": "var(--fallback-b3, oklch(var(--b3) / 0.2))",
          "--btn-focus-scale": "0.95",
          "--tab-border": "2px",
        },
      },
    ],
  },
};
